version: "3"

services:
  db:
    container_name: CQ-db
    volumes:
      - mysql-local:/var/lib/mysql
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    container_name: CQ-app
    build: ./go
    ports:
      - "8080:8080"
    volumes:
      - ./go:/app
    depends_on:
      - db

volumes:
  mysql-local:
