version: "3"

services:
  db:
    container_name: CQ-db
    volumes:
      - mysql-local:/var/lib/mysql
    build: ./mysql
    ports:
      - "3306:3306"
    env_file: .env

  web:
    container_name: CQ-app
    build: ./go
    ports:
      - "8080:8080"
    volumes:
      - ./go:/app
    depends_on:
      - db
    env_file: .env

volumes:
  mysql-local:
